/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.UsuarioDAO;
import DAO.moduloConexao;
import Model.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class TelaUsuario_senha extends javax.swing.JFrame {
    
    public TelaUsuario_senha() {
        initComponents();

        this.setLocationRelativeTo(null);
    }
    void Volta_TelaConta() {

        TelaUsuario TelaUser = null;

        if (TelaUser== null) {

            TelaUser = new TelaUsuario();

            TelaUser.setVisible(true);

            TelaUser.receberID(txt_id.getText());

        } else {

            TelaUser.setVisible(true);

            TelaUser.setState(TelaUser.NORMAL); // olha essa linha

            TelaUser.receberID(txt_id.getText());

        }

        this.dispose();
        
    }
    
    void update_Senha() {
        
            String senha1 = new String(this.txt_NovaSenha.getPassword());
            String senha2 = new String(this.txt_ConfirmaSenha.getPassword());
            int id = Integer.parseInt(this.txt_id.getText());
            
            Usuario senhaUser = new Usuario(
                senha1,
                senha2,
                id
                
        );

        UsuarioDAO UserSenhaDAO = new UsuarioDAO();

        try {
            
            if (UserSenhaDAO.valida_UpdateSenha(senha1, senha2)){
                
                if(senhaUser.validaTamSenha(senha1)){
                    
                    UserSenhaDAO.UpdateSenha(senhaUser);
                    JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso");
                    Volta_TelaConta();
                    
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Falha,A senha dever ter no mínimo 6 caracteres!");
                }
                
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Dados Inválidos, impossível atualizar!!");
                
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_NovaSenha = new javax.swing.JPasswordField();
        txt_ConfirmaSenha = new javax.swing.JPasswordField();
        btn_alteraSenha = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        jPasswordField3.setText("jPasswordField3");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel4.setText("Nova Senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 0, 140, 26);

        jLabel1.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        jLabel1.setText("Nova senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 160, 80, 17);

        jLabel2.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        jLabel2.setText("Repita a nova senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 210, 120, 17);

        txt_NovaSenha.setBackground(new java.awt.Color(187, 210, 240));
        txt_NovaSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_NovaSenha);
        txt_NovaSenha.setBounds(310, 180, 200, 27);
        txt_NovaSenha.getAccessibleContext().setAccessibleName("Senha");
        txt_NovaSenha.getAccessibleContext().setAccessibleDescription("Digite a nova senha aqui");

        txt_ConfirmaSenha.setBackground(new java.awt.Color(187, 210, 240));
        txt_ConfirmaSenha.setColumns(10);
        txt_ConfirmaSenha.setToolTipText("senha");
        txt_ConfirmaSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_ConfirmaSenha);
        txt_ConfirmaSenha.setBounds(310, 230, 200, 27);
        txt_ConfirmaSenha.getAccessibleContext().setAccessibleName("Repetir a senha");
        txt_ConfirmaSenha.getAccessibleContext().setAccessibleDescription("Digite a nova senha aqui");

        btn_alteraSenha.setBackground(new java.awt.Color(105, 69, 219));
        btn_alteraSenha.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btn_alteraSenha.setForeground(new java.awt.Color(255, 255, 255));
        btn_alteraSenha.setText("Salvar");
        btn_alteraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alteraSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alteraSenha);
        btn_alteraSenha.setBounds(360, 300, 100, 27);
        btn_alteraSenha.getAccessibleContext().setAccessibleDescription("Botão de confirmação");

        btn_voltar.setBackground(new java.awt.Color(105, 69, 219));
        btn_voltar.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar);
        btn_voltar.setBounds(40, 60, 100, 27);
        btn_voltar.getAccessibleContext().setAccessibleDescription("Botão para voltar sem cadastrar nova senha");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/teste_icon_pedmeia1.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 360, 140, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_principal.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1920, 1080);
        getContentPane().add(txt_id);
        txt_id.setBounds(0, 0, 54, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alteraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alteraSenhaActionPerformed
        // TODO add your handling code here:
        update_Senha();
    }//GEN-LAST:event_btn_alteraSenhaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        Volta_TelaConta();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario_senha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alteraSenha;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField txt_ConfirmaSenha;
    private javax.swing.JPasswordField txt_NovaSenha;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

public void receberID(String recebe){

        txt_id.setText(recebe);
    }

}
