/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.moduloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class TelaDespesa_Consulta extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TelaDespesa_Consulta() {
        initComponents();
        conexao = moduloConexao.conector();
        this.setLocationRelativeTo(null);
        txt_id.setVisible(false);
    }
       
    void voltaTelaDespesa(){

          TelaDespesa Tela_despesa = null;

        if (Tela_despesa == null) {

            Tela_despesa = new TelaDespesa();

            Tela_despesa.setVisible(true);

            Tela_despesa.receberID(txt_id.getText());

        } else {

            Tela_despesa.setVisible(true);

            Tela_despesa.setState(TelaPrincipal.NORMAL);

            Tela_despesa.receberID(txt_id.getText());

        }
        this.dispose();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultaDespesa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel2.setText("Consultar Despesa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 0, 180, 20);

        jtConsultaDespesa.setBackground(new java.awt.Color(187, 210, 240));
        jtConsultaDespesa.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        jtConsultaDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Categoria", "Descrição", "Forma de Pagamento", "Status", "N° do Cartão", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtConsultaDespesa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 640, 170);

        jButton1.setBackground(new java.awt.Color(105, 69, 219));
        jButton1.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 40, 100, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/teste_icon_pedmeia1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 290, 150, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_principal.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);
        getContentPane().add(txt_id);
        txt_id.setBounds(168, 44, 105, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //consulta
        DefaultTableModel mp1 = (DefaultTableModel) jtConsultaDespesa.getModel();
        
        int l = mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                //Limpa tabela sempre que for fazer uma nova consulta
                ((DefaultTableModel) jtConsultaDespesa.getModel()).removeRow(l - 1);
                
                //Menos um pois a primeira linha é a linha zero
                l--;
            }
        }
        
        try{
            
            //String sql = "select valor, categoria, descricao, f_pagamento, estatus, num_cartao from despesa where conta_id_conta=?";
            String sql = "select valor, categoria,descricao, f_pagamento, estatus, num_cartao, dia, mes, ano from (despesa D JOIN despesa_data Ddt ON D.despesa_data_cod_despesa = Ddt.cod_despesa )where conta_id_conta=?";
            
            pst = conexao.prepareStatement(sql);
            
            pst.setInt(1, Integer.parseInt(txt_id.getText()));

            DefaultTableModel mp = (DefaultTableModel) jtConsultaDespesa.getModel();
            
            rs = pst.executeQuery();    

            while(rs.next()) {
                
                String Col0 = rs.getString("valor");
                String Col1 = rs.getString("categoria");
                String Col2 = rs.getString("descricao");
                String Col3 = rs.getString("f_pagamento");
                String Col4 = rs.getString("estatus");
                String Col5 = rs.getString("num_cartao");
                String Col6 = rs.getString("dia");
                String Col7 = rs.getString("mes");
                String Col8 = rs.getString("ano");
                
                String data = null;
                data = Col6 +"/" + Col7 + "/" + Col8;
                System.out.println("Data "+data);
                //Redimensiona a tabela
                //TamanhoColunas();
                if(Col3.equals("DINHEIRO")){
                    Col5 = "-";                    
                    
                    mp.addRow(new String[] {Col0,Col1,Col2, Col3, Col4, Col5, data});
                }else{
                    mp.addRow(new String[] {Col0,Col1,Col2, Col3, Col4, Col5, data});
                }
                
                
            }
            
            
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
        jtConsultaDespesa.setAutoCreateRowSorter(true);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        voltaTelaDespesa();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDespesa_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDespesa_Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtConsultaDespesa;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

public void receberID(String recebe){

        txt_id.setText(recebe);
    }

}
