/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.UsuarioDAO;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Tela_RecuperaSenha extends javax.swing.JFrame {

    /**
     * Creates new form Tela_RecuperaSenha
     */
    public Tela_RecuperaSenha() {
        initComponents();
    }
    
    void NovaSenha(int id) {
        
        Tela_NovaSenha Tela_NovaSenha = null;

        if (Tela_NovaSenha == null) {

            Tela_NovaSenha = new Tela_NovaSenha();

            Tela_NovaSenha.setVisible(true);

            Tela_NovaSenha.recebeID(id);

        } else {

            Tela_NovaSenha.setVisible(true);

            Tela_NovaSenha.setState(TelaPrincipal.NORMAL);

            Tela_NovaSenha.recebeID(id);

        }

        this.dispose();
    }
    
    void volta_telaLogin(){
        
         TelaLogin telaDeLogin= new TelaLogin();
         telaDeLogin.setVisible(true);
         this.dispose();
         
    }
    
    public void RecuperaSenha() {
        
        Usuario user = new Usuario.UsuarioBuild(txt_RecuperaSenha_email.getText()).build();
          
        
        UsuarioDAO userDAO = new UsuarioDAO();

        try {
                if(userDAO.verificaEmailExiste(user.getEmail())){
                   
                    int id = userDAO.consultaId(user.getEmail());
                    NovaSenha(id);
                    
                    
                }else{
                     JOptionPane.showMessageDialog(null, "Usuário não existe");
                    volta_telaLogin();
                }
                
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageTitle = new javax.swing.JLabel();
        emailTitle = new javax.swing.JLabel();
        txt_RecuperaSenha_email = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperação de Senha");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pageTitle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        pageTitle.setText("Recuperação de Senha");
        getContentPane().add(pageTitle);
        pageTitle.setBounds(290, 0, 210, 27);

        emailTitle.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        emailTitle.setText("Informe seu Email");
        getContentPane().add(emailTitle);
        emailTitle.setBounds(210, 170, 120, 27);

        txt_RecuperaSenha_email.setBackground(new java.awt.Color(187, 210, 240));
        txt_RecuperaSenha_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_RecuperaSenha_email);
        txt_RecuperaSenha_email.setBounds(210, 190, 370, 27);

        checkButton.setBackground(new java.awt.Color(105, 69, 219));
        checkButton.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        checkButton.setText("Verificar");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton);
        checkButton.setBounds(330, 260, 140, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/waning_back.png"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background);
        background.setBounds(-380, -130, 1280, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        RecuperaSenha();
    }//GEN-LAST:event_checkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_RecuperaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JTextField txt_RecuperaSenha_email;
    // End of variables declaration//GEN-END:variables
}
