/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ControlerUser;
import Model.Usuario;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class TelaUsuario extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaUsuario_consulta
     */
    public TelaUsuario() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtNome.setEditable(false);
        txtEmail.setEditable(false);
        txtSenha.setEditable(false);
        
        txt_id.setVisible(false);
        
    }
    
     void TelaPrincipal(){
         
         TelaPrincipal TelaPrincipal = null;
         
         if (TelaPrincipal == null) {

             TelaPrincipal = new TelaPrincipal();

             TelaPrincipal.setVisible(true);

             TelaPrincipal.receberID(txt_id.getText());

         } else {

             TelaPrincipal.setVisible(true);

             TelaPrincipal.setState(TelaPrincipal.NORMAL);

             TelaPrincipal.receberID(txt_id.getText());
         }
         
         this.dispose();
    }
    
     void TelaUsuario_senha(){
         
         TelaUsuario_senha TelaUser_senha = null;
         
         if (TelaUser_senha == null) {

             TelaUser_senha = new TelaUsuario_senha();

             TelaUser_senha.setVisible(true);

             TelaUser_senha.receberID(txt_id.getText());

         } else {

             TelaUser_senha.setVisible(true);

             TelaUser_senha.setState(TelaPrincipal.NORMAL);

             TelaUser_senha.receberID(txt_id.getText());
         }
         
         this.dispose();
    }
     
    void AtualizarUsuario(){
     
            int id = Integer.parseInt(this.txt_id.getText());
                Usuario user = new Usuario.UsuarioBuild(txtEmail.getText())
                    .IdConta(id)
                    .Nome(txtNome.getText())
                    .build();

        try {
            
            if(user.UpdateEhVazio()){
                JOptionPane.showMessageDialog(null, "Nenehum campo ser vazio para realizar o update");
                return;
            }
            
            ControlerUser.AtualizarUsuario(user);
            

        } catch (HeadlessException e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }
     }
    
    void TelaLogin(){
        
         TelaLogin telaDeLogin= new TelaLogin();
         telaDeLogin.setVisible(true);
         this.dispose();
         
    }
    
    void ApagarUsuario(){
        
        try{
            
            ControlerUser.ApagarUsuario(Integer.parseInt(txt_id.getText()));
            
        }catch(NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pageTitle = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JToggleButton();
        btn_update = new javax.swing.JButton();
        nameTitle = new javax.swing.JLabel();
        emailTitle = new javax.swing.JLabel();
        passwdTitle = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados do Usuário");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pageTitle.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        pageTitle.setText("Dados do Usuário");
        getContentPane().add(pageTitle);
        pageTitle.setBounds(310, 0, 170, 24);

        txtNome.setBackground(new java.awt.Color(187, 210, 240));
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtNome);
        txtNome.setBounds(200, 150, 400, 27);

        txtEmail.setBackground(new java.awt.Color(187, 210, 240));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtEmail);
        txtEmail.setBounds(200, 210, 400, 27);

        txtSenha.setBackground(new java.awt.Color(187, 210, 240));
        txtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtSenha);
        txtSenha.setBounds(200, 270, 400, 27);

        startButton.setBackground(new java.awt.Color(105, 69, 219));
        startButton.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Início");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        startButton.setBounds(40, 50, 100, 25);

        btnAlterar.setBackground(new java.awt.Color(105, 69, 219));
        btnAlterar.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar Senha");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(340, 380, 140, 27);

        btnExcluir.setBackground(new java.awt.Color(210, 59, 233));
        btnExcluir.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(340, 420, 140, 27);

        btn_update.setBackground(new java.awt.Color(105, 69, 219));
        btn_update.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Alterar");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(340, 340, 140, 27);

        nameTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        nameTitle.setText("Nome: ");
        getContentPane().add(nameTitle);
        nameTitle.setBounds(200, 130, 70, 16);

        emailTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        emailTitle.setText("Email:");
        getContentPane().add(emailTitle);
        emailTitle.setBounds(200, 190, 60, 16);

        passwdTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        passwdTitle.setText("Senha:");
        getContentPane().add(passwdTitle);
        passwdTitle.setBounds(200, 250, 70, 20);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Back-2.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);
        getContentPane().add(txt_id);
        txt_id.setBounds(0, 0, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try {

            Usuario usuario = ControlerUser.GetUsuario(txt_id.getText());

            txtNome.setText(usuario.getNome());
            txtEmail.setText(usuario.getEmail());
            txtSenha.setText(usuario.getSenha());

        } catch (NullPointerException ex) {

            JOptionPane.showMessageDialog(this, "Erro ao inserir os dados nos campos!! -> " + ex.getMessage());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        
        TelaPrincipal();
    }//GEN-LAST:event_startButtonActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        TelaUsuario_senha();
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        
        if(btn_update.getText().equals("Alterar")){
            
            btn_update.setText("Atualizar");
            
            txtNome.setEditable(true);
            txtEmail.setEditable(true);
            txtSenha.setEditable(true);
        
        }else{
            
            btn_update.setText("Alterar");
            
            txtNome.setEditable(false);
            txtEmail.setEditable(false);
            txtSenha.setEditable(false);
            
            AtualizarUsuario();
            
        }
        
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        ApagarUsuario();
        TelaLogin();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JLabel passwdTitle;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

    public void receberID(String recebe){

        txt_id.setText(recebe);
    }
}