/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.CartaoCreditoDAO;
import Model.CartaoCredito;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan
 */
public class TelaCartaoCredito_ListaFaturas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCartaoCredito_ListaFaturas
     */
    public TelaCartaoCredito_ListaFaturas() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    
    void cartao_credito() {

        TelaCartao_credito TelaCartao_credito = null;

        if (TelaCartao_credito == null) {

            TelaCartao_credito = new TelaCartao_credito();

            TelaCartao_credito.setVisible(true);

            TelaCartao_credito.receberID(txt_id.getText());

        } else {

            TelaCartao_credito.setVisible(true);

            TelaCartao_credito.setState(TelaPrincipal.NORMAL);

            TelaCartao_credito.receberID(txt_id.getText());

        }

        this.dispose();
    }
    

     void RecarregaTabela_CartaoCC_Faturas() {

        boolean salvaLinhaAtiva = false;
        
        DefaultTableModel mp1 = (DefaultTableModel) jtFaturas.getModel();

        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                //Limpa tabela sempre que for fazer uma nova consulta
                ((DefaultTableModel) jtFaturas.getModel()).removeRow(l - 1);

                //Menos um pois a primeira linha é a linha zero
                l--;
            }
        }

        try {

            CartaoCreditoDAO cartao_c = new CartaoCreditoDAO();

            DefaultTableModel mp = (DefaultTableModel) jtFaturas.getModel();

            LinkedList<CartaoCredito> lista_CC = cartao_c.CarregaTabela_Cartao_C(Integer.parseInt(txt_id.getText()));

            for (CartaoCredito cartao : lista_CC) {

                String Col0 = Long.toString(cartao.getN_cartao_credito());
                String Col1 = Integer.toString(cartao.getDia_fatura());
                String Col2 = Float.toString(cartao.getValor_fatura());
                String Col3 = cartao.getBandeira();

                mp.addRow(new String[]{Col0, Col1, Col2, Col3});

            }

            lista_CC.clear();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageTitle = new javax.swing.JLabel();
        dataTable = new javax.swing.JScrollPane();
        jtFaturas = new javax.swing.JTable();
        selectorType = new javax.swing.JComboBox<>();
        findField = new javax.swing.JTextField();
        seletorUp = new javax.swing.JRadioButton();
        seletorDown = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        findTitle = new javax.swing.JLabel();
        selectorTitle = new javax.swing.JLabel();
        orientationTitle = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        PageTitle.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        PageTitle.setText("Lista de Faturas");
        getContentPane().add(PageTitle);
        PageTitle.setBounds(330, 0, 170, 27);

        jtFaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Cartão Crédito", "Dia da Fatura", "Valor da Fatura", "Bandeira"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setViewportView(jtFaturas);

        getContentPane().add(dataTable);
        dataTable.setBounds(25, 190, 750, 232);

        selectorType.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        selectorType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nº Cartão", "Dia da Fatura", "Valor da Fatura", "Bandeira", " ", " ", " " }));
        getContentPane().add(selectorType);
        selectorType.setBounds(30, 120, 130, 27);

        findField.setColumns(20);
        findField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFieldActionPerformed(evt);
            }
        });
        findField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findFieldKeyReleased(evt);
            }
        });
        getContentPane().add(findField);
        findField.setBounds(170, 120, 330, 27);

        seletorUp.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        seletorUp.setText("Ascendente");
        seletorUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorUpActionPerformed(evt);
            }
        });
        getContentPane().add(seletorUp);
        seletorUp.setBounds(510, 120, 100, 27);

        seletorDown.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        seletorDown.setText("Descendente");
        seletorDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDownActionPerformed(evt);
            }
        });
        getContentPane().add(seletorDown);
        seletorDown.setBounds(610, 120, 110, 27);

        backButton.setBackground(new java.awt.Color(105, 69, 219));
        backButton.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(30, 40, 100, 27);

        searchButton.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        searchButton.setBorderPainted(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(730, 120, 40, 40);

        findTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        findTitle.setText("Digite sua pesquisa aqui");
        getContentPane().add(findTitle);
        findTitle.setBounds(170, 100, 160, 27);

        selectorTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        selectorTitle.setText("Pesquisar por");
        getContentPane().add(selectorTitle);
        selectorTitle.setBounds(30, 100, 100, 27);

        orientationTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        orientationTitle.setText("Ordenação");
        getContentPane().add(orientationTitle);
        orientationTitle.setBounds(510, 100, 80, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Back-2.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(150, 175, 231));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(0, 0, 60, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cartao_credito();
    }//GEN-LAST:event_backButtonActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        RecarregaTabela_CartaoCC_Faturas();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void findFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findFieldActionPerformed

    private void findFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findFieldKeyReleased
        // TODO add your handling code here

        if (findField.getText().isEmpty()) {
            RecarregaTabela_CartaoCC_Faturas();
        }
    }//GEN-LAST:event_findFieldKeyReleased

    private void seletorUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorUpActionPerformed
        // TODO add your handling code here:

        if (seletorUp.isSelected()) {

            seletorDown.setSelected(false);

        }
    }//GEN-LAST:event_seletorUpActionPerformed

    private void seletorDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDownActionPerformed
        // TODO add your handling code here:

        if (seletorDown.isSelected()) {

            seletorUp.setSelected(false);

        }
    }//GEN-LAST:event_seletorDownActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:

        if (seletorUp.isSelected() || seletorDown.isSelected()) {

            boolean ordenar = true;

            String tipo = "";

            String escolha = selectorType.getSelectedItem().toString().trim();

            if (escolha.equals("Nº Cartão")) {
                tipo = " " + "n_cartao_credito";
            }

            if (escolha.equals("Dia da Fatura")) {
                tipo = " " + "dia_fatura";
            }

            if (escolha.equals("Valor da Fatura")) {
                tipo = " " + "valor_fatura";
            }

            if (escolha.equals("Bandeira")) {
                tipo = " " + "bandeira";
            }

            if (seletorUp.isSelected()) {

                ordenar = true;

            } else {

                ordenar = false;
            }

            String argumento = findField.getText();

            DefaultTableModel mp1 = (DefaultTableModel) jtFaturas.getModel();

            int l = mp1.getRowCount();

            if (l > 0) {
                while (l > 0) {
                    //Limpa tabela sempre que for fazer uma nova consulta
                    ((DefaultTableModel) jtFaturas.getModel()).removeRow(l - 1);

                    //Menos um pois a primeira linha é a linha zero
                    l--;
                }
            }

            try {

                CartaoCreditoDAO cartao_c = new CartaoCreditoDAO();

                DefaultTableModel mp = (DefaultTableModel) jtFaturas.getModel();

                LinkedList<CartaoCredito> lista_CC_Faturas = cartao_c.ConsultaCartao_C(tipo, argumento, Integer.parseInt(txt_id.getText()), ordenar);

                for (CartaoCredito cartao : lista_CC_Faturas) {

                    String Col0 = Long.toString(cartao.getN_cartao_credito());
                    String Col1 = Integer.toString(cartao.getDia_fatura());
                    String Col2 = Float.toString(cartao.getValor_fatura());
                    String Col3 = cartao.getBandeira();

                    mp.addRow(new String[]{Col0, Col1, Col2, Col3});

                }

                lista_CC_Faturas.clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());

            }

        } else {

            JOptionPane.showMessageDialog(null, "Tipo de Ordenação Obrigatório");

        }

    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartaoCredito_ListaFaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartaoCredito_ListaFaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartaoCredito_ListaFaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartaoCredito_ListaFaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCartaoCredito_ListaFaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PageTitle;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane dataTable;
    private javax.swing.JTextField findField;
    private javax.swing.JLabel findTitle;
    private javax.swing.JTable jtFaturas;
    private javax.swing.JLabel orientationTitle;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel selectorTitle;
    private javax.swing.JComboBox<String> selectorType;
    private javax.swing.JRadioButton seletorDown;
    private javax.swing.JRadioButton seletorUp;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

   public void receberID(String recebe) {

        txt_id.setText(recebe);
    }


}
