/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ControlerCartaoDebito;
import Model.CartaoDebito;
import Utilities.Validacao;
import com.mysql.cj.util.StringUtils;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class TelaAtualizarCartaoDebito extends javax.swing.JFrame {
    
    private CartaoDebito cartaoDebito = null;

    /**
     * Creates new form TelaAtualizarCartaoDebito
     */
    public TelaAtualizarCartaoDebito() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    void TelaCartaoDebito() {

        TelaCartao_debito TelaCartao_debito = null;

        if (TelaCartao_debito == null) {

            TelaCartao_debito = new TelaCartao_debito();

            TelaCartao_debito.setVisible(true);

            TelaCartao_debito.receberID(Integer.toString(cartaoDebito.getId_conta()));

        } else {

            TelaCartao_debito.setVisible(true);

            TelaCartao_debito.setState(TelaPrincipal.NORMAL);

             TelaCartao_debito.receberID(Integer.toString(cartaoDebito.getId_conta()));

        }

        this.dispose();
    }
    
    void AtualizarCartaoDebito() {
        
        if (StringUtils.isNullOrEmpty(txt_NumCartaoD.getText()) ||
            StringUtils.isNullOrEmpty(txt_Valor.getText()) ||
            StringUtils.isNullOrEmpty(txt_Bandeira.getText())) 
        {
            JOptionPane.showMessageDialog(this, "Nenhum Campo pode ser nulo no Update", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!(Validacao.isNumeric(txt_NumCartaoD.getText()) && Validacao.isNumeric(txt_Valor.getText()))) {
            JOptionPane.showMessageDialog(this, "Informe um valor numérico válido!!", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        CartaoDebito cartao_d = 
            new CartaoDebito.CartaoDebitoBuild(
                 Long.parseLong(txt_NumCartaoD.getText()))
                .ValorAtual(Float.parseFloat(txt_Valor.getText()))
                .Bandeira(txt_Bandeira.getText())
                .IdConta(this.cartaoDebito.getId_conta())
                .NumCartaoAux(this.cartaoDebito.getN_cartao_debito())
                .build();
        /*
        CartaoDebito cartao_d = 
            new CartaoDebito(
                Long.parseLong(txt_NumCartaoD.getText()),
                Float.parseFloat(txt_Valor.getText()),
                txt_Bandeira.getText(),
                this.cartaoDebito.getId_conta(),
                this.cartaoDebito.getN_cartao_debito()
            );
        */
        if (!(cartao_d.verifica_num_cartao_deb())) {
            
            JOptionPane.showMessageDialog(this, "Número do cartão de débito inválido", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Verifica se o número do cartao de débito foi modificado
        if(cartao_d.getN_cartao_debito() != this.cartaoDebito.getN_cartao_debito())
        {
            //Verifica se o novo número já existe
            if(ControlerCartaoDebito.GetCartaoDebito(cartao_d.getN_cartao_debito(), cartao_d.getId_conta()) != null )
            {
                JOptionPane.showMessageDialog(null, "Número de Cartão de Débito já existe!!\n Tente outro número", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                return;
            } 
        }

        try {

            if (cartao_d.verifica_bandeira() && cartao_d.verifica_valor_atual()) {

                ControlerCartaoDebito.AtualizarCartaoDebito(cartao_d);

            } else 
                JOptionPane.showMessageDialog(this, "Dados Inválidos, impossível atuzalizar!!", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            
        } catch (HeadlessException | NullPointerException | NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardNumTitle = new javax.swing.JLabel();
        txt_NumCartaoD = new javax.swing.JTextField();
        valueTitle = new javax.swing.JLabel();
        txt_Valor = new javax.swing.JTextField();
        flagTitle = new javax.swing.JLabel();
        txt_Bandeira = new javax.swing.JTextField();
        cardNumTitle1 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btnReceitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        cardNumTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        cardNumTitle.setText("Número do cartão");
        getContentPane().add(cardNumTitle);
        cardNumTitle.setBounds(22, 71, 140, 27);

        txt_NumCartaoD.setBackground(new java.awt.Color(187, 210, 240));
        txt_NumCartaoD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_NumCartaoD);
        txt_NumCartaoD.setBounds(22, 91, 400, 27);

        valueTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        valueTitle.setText("Valor");
        getContentPane().add(valueTitle);
        valueTitle.setBounds(22, 121, 100, 27);

        txt_Valor.setBackground(new java.awt.Color(187, 210, 240));
        txt_Valor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_Valor);
        txt_Valor.setBounds(22, 141, 400, 27);

        flagTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        flagTitle.setText("Bandeira");
        getContentPane().add(flagTitle);
        flagTitle.setBounds(22, 171, 70, 27);

        txt_Bandeira.setBackground(new java.awt.Color(187, 210, 240));
        txt_Bandeira.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_Bandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BandeiraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Bandeira);
        txt_Bandeira.setBounds(22, 191, 400, 27);

        cardNumTitle1.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        cardNumTitle1.setText("Atualizar Cartao Debito");
        getContentPane().add(cardNumTitle1);
        cardNumTitle1.setBounds(320, 0, 140, 27);

        btn_update.setBackground(new java.awt.Color(105, 69, 219));
        btn_update.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Atualizar");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(135, 274, 140, 25);

        btnReceitas.setBackground(new java.awt.Color(105, 69, 219));
        btnReceitas.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btnReceitas.setForeground(new java.awt.Color(255, 255, 255));
        btnReceitas.setText("Voltar");
        btnReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReceitas);
        btnReceitas.setBounds(328, 274, 111, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_BandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BandeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BandeiraActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        AtualizarCartaoDebito();
        TelaCartaoDebito();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btnReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceitasActionPerformed
        // TODO add your handling code here:
        TelaCartaoDebito();
    }//GEN-LAST:event_btnReceitasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            txt_NumCartaoD.setText(Long.toString(cartaoDebito.getN_cartao_debito()));
            txt_Valor.setText(Float.toString(cartaoDebito.getValor_atual()));
            txt_Bandeira.setText(cartaoDebito.getBandeira());
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCartaoDebito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCartaoDebito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCartaoDebito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCartaoDebito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaAtualizarCartaoDebito().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceitas;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel cardNumTitle;
    private javax.swing.JLabel cardNumTitle1;
    private javax.swing.JLabel flagTitle;
    private javax.swing.JTextField txt_Bandeira;
    private javax.swing.JTextField txt_NumCartaoD;
    private javax.swing.JTextField txt_Valor;
    private javax.swing.JLabel valueTitle;
    // End of variables declaration//GEN-END:variables


public void receberCartaoDebito(CartaoDebito cartaoDebito) {
    
   this.cartaoDebito = cartaoDebito;
}

}