/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Categoria;
import DAO.CategoriaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class TelaCategoria_cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form TelaCategoria_cadastrar
     */
    public TelaCategoria_cadastrar() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }
    
    void inicio(){

         TelaPrincipal TelaPrincipal = null;

         if (TelaPrincipal == null) {

             TelaPrincipal = new TelaPrincipal();

             TelaPrincipal.setVisible(true);

             TelaPrincipal.receberID(txt_id.getText());

         } else {

             TelaPrincipal.setVisible(true);

             TelaPrincipal.setState(TelaPrincipal.NORMAL);

             TelaPrincipal.receberID(txt_id.getText());
         }

         this.dispose();
    }
    
    void volta_telaCategoria() {


        TelaCategoria TelaCategoria = null;

        if (TelaCategoria == null) {

            TelaCategoria = new TelaCategoria();

            TelaCategoria.setVisible(true);

            TelaCategoria.receberID(txt_id.getText());

        } else {

            TelaCategoria.setVisible(true);

            TelaCategoria.setState(TelaPrincipal.NORMAL);

            TelaCategoria.receberID(txt_id.getText());

        }

        this.dispose();
    }
    
    void limpa_campo(){
        
        txt_categoria.setText("");
        
    }
    
    
   public void cadastro_categoria() {
        
        Categoria cartategoria_aux = new Categoria();
          
        Categoria categoria = new Categoria(
              txt_categoria.getText(),
              Integer.parseInt(txt_id.getText())
                
        );
        
        CategoriaDAO categoriaDAO = new CategoriaDAO();

        try {
            
                categoriaDAO.CadastrarCategoria(categoria);
                 volta_telaCategoria();
                
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_categoria = new javax.swing.JTextField();
        btn_inicio = new javax.swing.JButton();
        btn_cadastarCategoria = new javax.swing.JButton();
        categoryTitle = new javax.swing.JLabel();
        pageTitle = new javax.swing.JLabel();
        iconPed12 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(txt_categoria);
        txt_categoria.setBounds(160, 130, 500, 27);

        btn_inicio.setBackground(new java.awt.Color(105, 69, 219));
        btn_inicio.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btn_inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicio.setText("Inicio");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inicio);
        btn_inicio.setBounds(40, 50, 90, 27);

        btn_cadastarCategoria.setBackground(new java.awt.Color(105, 69, 219));
        btn_cadastarCategoria.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btn_cadastarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastarCategoria.setText("Cadastrar");
        btn_cadastarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastarCategoria);
        btn_cadastarCategoria.setBounds(310, 170, 200, 27);

        categoryTitle.setText("Nova Categoria");
        getContentPane().add(categoryTitle);
        categoryTitle.setBounds(160, 110, 200, 27);

        pageTitle.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        pageTitle.setText("Cadastrar Categoria");
        getContentPane().add(pageTitle);
        pageTitle.setBounds(320, 0, 210, 27);

        iconPed12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-280x200.png"))); // NOI18N
        getContentPane().add(iconPed12);
        iconPed12.setBounds(200, 210, 420, 350);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Back-2.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);
        getContentPane().add(txt_id);
        txt_id.setBounds(0, 0, 49, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastarCategoriaActionPerformed
        
        
        cadastro_categoria();
        
        
    }//GEN-LAST:event_btn_cadastarCategoriaActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
        
        inicio();
        
    }//GEN-LAST:event_btn_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCategoria_cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_cadastarCategoria;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JLabel categoryTitle;
    private javax.swing.JLabel iconPed12;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

public void receberID(String recebe) {

        txt_id.setText(recebe);
}



}
