/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.UsuarioDAO;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Tela_RecuperaSenha extends javax.swing.JFrame {

    /**
     * Creates new form Tela_RecuperaSenha
     */
    public Tela_RecuperaSenha() {
        initComponents();
    }
    
    /*
    void NovaSenha(int id) {

        String id_aux = Integer.toString(id);
        
        TelaUsuario_senha TelaUsuario_senha = null;

        if (TelaUsuario_senha == null) {

            TelaUsuario_senha = new TelaUsuario_senha();

            TelaUsuario_senha.setVisible(true);

            TelaUsuario_senha.receberID(id_aux);

        } else {

            TelaUsuario_senha.setVisible(true);

            TelaUsuario_senha.setState(TelaPrincipal.NORMAL);

            TelaUsuario_senha.receberID(id_aux);

        }

        this.dispose();
    }
    */
    
    void NovaSenha(int id) {
        
        Tela_NovaSenha Tela_NovaSenha = null;

        if (Tela_NovaSenha == null) {

            Tela_NovaSenha = new Tela_NovaSenha();

            Tela_NovaSenha.setVisible(true);

            Tela_NovaSenha.recebeID(id);

        } else {

            Tela_NovaSenha.setVisible(true);

            Tela_NovaSenha.setState(TelaPrincipal.NORMAL);

            Tela_NovaSenha.recebeID(id);

        }

        this.dispose();
    }
    
    void volta_telaLogin(){
        
         TelaLogin telaDeLogin= new TelaLogin();
         telaDeLogin.setVisible(true);
         this.dispose();
         
    }
    
    public void RecuperaSenha() {
        
        Usuario user = new Usuario(
            txt_RecuperaSenha_email.getText()
        );
          
        
        UsuarioDAO userDAO = new UsuarioDAO();

        try {
                if(userDAO.verificaEmailExiste(user.getEmail())){
                   
                    int id = userDAO.consultaId(user.getEmail());
                    NovaSenha(id);
                    
                    
                }else{
                     JOptionPane.showMessageDialog(null, "Usuário não existe");
                    volta_telaLogin();
                }
                
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_RecuperaSenha_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Informe seu Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 110, 17);
        getContentPane().add(txt_RecuperaSenha_email);
        txt_RecuperaSenha_email.setBounds(100, 130, 198, 21);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 210, 85, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Back-2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        jLabel3.setText("Recuperação de Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 0, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RecuperaSenha();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_RecuperaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_RecuperaSenha_email;
    // End of variables declaration//GEN-END:variables
}
