/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ControlerUser;
import javax.swing.JOptionPane;
import Model.Usuario;
import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author pc
 */
public class TelaLogin extends javax.swing.JFrame {
    /**
     * Creates new form TelaLogin
     */
    
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public void logar() throws SQLException{   
        
       Usuario user = new Usuario.UsuarioBuild(
               txtEmail.getText())
                .Senha(txtSenha.getText())
                .build();
        
        try {
            
            if(ControlerUser.Logar(user)){
                
                TelaPrincipal TelaPrincipal = null;

                if (TelaPrincipal == null) {

                    TelaPrincipal telaPrincipal = new TelaPrincipal();

                    telaPrincipal.setVisible(true);

                    String id = Integer.toString(user.getId_conta());

                    telaPrincipal.receberID(id);
                    
                } else {

                    TelaPrincipal.setVisible(true);

                    TelaPrincipal.setState(TelaPrincipal.NORMAL);

                    String id = Integer.toString(user.getId_conta());

                    TelaPrincipal.receberID(id);
                }
                
                this.dispose();

            }else{
                JOptionPane.showMessageDialog(null, "Usuario ou senha inválido");
            }
        } catch (HeadlessException | NullPointerException e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    void cadastro(){
        
        try {

            TelaUsuario_cadastrar cadastroCliente = new TelaUsuario_cadastrar();
            cadastroCliente.setVisible(true);
            this.dispose();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    
    void Recupera_senha() {
        
        try {

            Tela_RecuperaSenha Tela_RecuperaSenha = null;

            if (Tela_RecuperaSenha == null) {

                Tela_RecuperaSenha = new Tela_RecuperaSenha();

                Tela_RecuperaSenha.setVisible(true);

            } else {

                Tela_RecuperaSenha.setVisible(true);

                Tela_RecuperaSenha.setState(TelaPrincipal.NORMAL);

            }

            this.dispose();

        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        recoveryPasswdButton = new javax.swing.JButton();
        iconPed12 = new javax.swing.JLabel();
        emailTitle = new javax.swing.JLabel();
        passwordTitle = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pageTitle.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        pageTitle.setText("Bem Vinde ao Ped1/2");
        getContentPane().add(pageTitle);
        pageTitle.setBounds(300, 0, 220, 30);

        txtEmail.setBackground(new java.awt.Color(187, 210, 240));
        txtEmail.setAlignmentX(1.0F);
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtEmail);
        txtEmail.setBounds(200, 210, 400, 27);
        txtEmail.getAccessibleContext().setAccessibleName("Digite seu e-mail ou login");
        txtEmail.getAccessibleContext().setAccessibleDescription("Digite aqui o seu e-mail ou seu login");

        txtSenha.setBackground(new java.awt.Color(187, 210, 240));
        txtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(200, 280, 400, 27);

        btnLogin.setBackground(new java.awt.Color(105, 69, 219));
        btnLogin.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(200, 330, 150, 27);

        btnCadastro.setBackground(new java.awt.Color(105, 69, 219));
        btnCadastro.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Novo Cadastro");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(450, 330, 150, 27);

        recoveryPasswdButton.setBackground(new java.awt.Color(210, 59, 235));
        recoveryPasswdButton.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        recoveryPasswdButton.setForeground(new java.awt.Color(255, 255, 255));
        recoveryPasswdButton.setText("Recuperação de senha");
        recoveryPasswdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoveryPasswdButtonActionPerformed(evt);
            }
        });
        getContentPane().add(recoveryPasswdButton);
        recoveryPasswdButton.setBounds(320, 490, 200, 27);

        iconPed12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-140x100.png"))); // NOI18N
        getContentPane().add(iconPed12);
        iconPed12.setBounds(320, 70, 140, 100);

        emailTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        emailTitle.setText("Email");
        getContentPane().add(emailTitle);
        emailTitle.setBounds(200, 190, 60, 27);

        passwordTitle.setFont(new java.awt.Font("Noto Serif", 1, 12)); // NOI18N
        passwordTitle.setText("Senha");
        getContentPane().add(passwordTitle);
        passwordTitle.setBounds(200, 260, 50, 27);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Back-2.png"))); // NOI18N
        background.setText("jLabel4");
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        try {
            logar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao logar" + ex.getMessage());
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        cadastro();

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void recoveryPasswdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoveryPasswdButtonActionPerformed
        // TODO add your handling code here:
        Recupera_senha();
    }//GEN-LAST:event_recoveryPasswdButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JLabel iconPed12;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JButton recoveryPasswdButton;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}