/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.UsuarioDAO;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Tela_NovaSenha extends javax.swing.JFrame {
    int salvaId = -1;
    /**
     * Creates new form Tela_NovaSenha
     */
    public Tela_NovaSenha() {
        initComponents();
    }
    
    void volta_telaLogin(){
        
         TelaLogin telaDeLogin= new TelaLogin();
         telaDeLogin.setVisible(true);
         this.dispose();
         
    }
    void recebeID(int id){
        salvaId = id;
    }
    
    void  nova_Senha() {
        
            String senha1 = new String(this.txt_NovaSenha.getPassword());
            String senha2 = new String(this.txt_ConfirmaSenha.getPassword());
            
            
            Usuario senhaUser = new Usuario(
                senha1,
                senha2,
                salvaId
                
        );

        UsuarioDAO UserSenhaDAO = new UsuarioDAO();

        try {
            
            if (UserSenhaDAO.valida_UpdateSenha(senha1, senha2)){
                
                if(senhaUser.validaTamSenha(senha1)){
                    
                    UserSenhaDAO.UpdateSenha(senhaUser);
                    JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso");
                    volta_telaLogin();
                    
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Falha,A senha dever ter no mínimo 6 caracteres!");
                }
                
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Dados Inválidos, impossível atualizar!!");
                
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pageTitle = new javax.swing.JLabel();
        txt_NovaSenha = new javax.swing.JPasswordField();
        txt_ConfirmaSenha = new javax.swing.JPasswordField();
        btn_AlteraSenha = new javax.swing.JButton();
        newPasswd = new javax.swing.JLabel();
        rpNewpasswd = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pageTitle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        pageTitle.setText("Atualização de Senha");
        getContentPane().add(pageTitle);
        pageTitle.setBounds(300, 0, 210, 26);

        txt_NovaSenha.setBackground(new java.awt.Color(187, 210, 240));
        txt_NovaSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_NovaSenha);
        txt_NovaSenha.setBounds(300, 130, 200, 27);

        txt_ConfirmaSenha.setBackground(new java.awt.Color(187, 210, 240));
        txt_ConfirmaSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_ConfirmaSenha);
        txt_ConfirmaSenha.setBounds(300, 180, 200, 27);

        btn_AlteraSenha.setBackground(new java.awt.Color(105, 69, 219));
        btn_AlteraSenha.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btn_AlteraSenha.setText("Salvar");
        btn_AlteraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlteraSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AlteraSenha);
        btn_AlteraSenha.setBounds(360, 270, 90, 27);

        newPasswd.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        newPasswd.setText("Nova Senha");
        getContentPane().add(newPasswd);
        newPasswd.setBounds(300, 110, 160, 17);

        rpNewpasswd.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        rpNewpasswd.setText("Repita a Senha");
        getContentPane().add(rpNewpasswd);
        rpNewpasswd.setBounds(300, 160, 160, 17);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Back-2.png"))); // NOI18N
        background.setText("jLabel4");
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AlteraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlteraSenhaActionPerformed
        // TODO add your handling code here:
        nova_Senha();
    }//GEN-LAST:event_btn_AlteraSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_NovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_NovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_NovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_NovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_NovaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_AlteraSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel newPasswd;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JLabel rpNewpasswd;
    private javax.swing.JPasswordField txt_ConfirmaSenha;
    private javax.swing.JPasswordField txt_NovaSenha;
    // End of variables declaration//GEN-END:variables
}
